networks:
  my_network:

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    container_name: mysql-db
    ports:
      - "3306:3306"
    networks:
      - my_network

  sut:
    image: sut
    container_name: sut
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/app
    ports:
      - "8080:8080"
    networks:
      - my_network


  gate-simulator:
    image: gate-simulator
    container_name: gate-simulator
    ports:
      - "9999:9999"
    networks:
      - my_network