networks:
  my_network:

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - my_network

  sut:
    image: sut
    container_name: sut
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - my_network
    environment:
      DB_URL: jdbc:postgresql://db:5432/app

  gate-simulator:
    image: gate-simulator
    container_name: gate-simulator
    ports:
      - "9999:9999"
    networks:
      - my_network